version: 2.1
orbs:
  node: circleci/node@5.0.2
workflows:
    example-workflow:
      jobs:
        - node/run:
            yarn-run: build 
        - node/run:
            yarn-run: format:check
        - node/run:
            yarn-run: lint